[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "turku-weather-bot"
version = "0.1.0"
dependencies = [
    "discord.py",
    "python-dotenv",
    "requests",
]
